language: java
sudo: required
jdk:
  - oraclejdk8
cache:
  directories:
   - $HOME/.m2

notifications:
  email:
    recipients:
      - vitruv-build@ira.uni-karlsruhe.de
  slack:
    secure: XQDTS0B4Wsa+pIGQwRzNidh1jegAI6SzS1ZSmoSUoH3bT8SpNStNvgSBXVxNhyIX2eiL/SbkDIXeo0kYL0yN0dSN0JV9KxEWLEBnMsVWSJTjN3PZ0Ot2j5ZN0+N4OiZNEgY7TXxu5hXPjItlCZR8t9HGkhbJA6ReUOwjbmteRgYhJnAl80xeHPqEq/7KWm01XBmVOxUvxJlzWmOdD/aav3ICoHA9iB9Bbs43LY2BYl2Dy2A9CIHG0S5V1mB8fidifCw3Hsqy1z8XZlYjiqkWjuTU7IFCvQjCeoevbu1PtBr6Q0P8HB67vyUo9TNEX8uH4QU9MyEkhAPodoaHvZEoAgzcNzcTGYKRjtCBAsApeW51UXTzcyEFS8WrRls9wrPw9AFyxeYtbvIiK1wFF3ViCEPJC9gdhd3atF3Y0lMyopyOpeS9TqP1W5ixYg9WorisAzopF3pmGNWIjG+Uy1vOqQ5HzUxbRfsr+BOZUDqlof3WmQ72IxGAXCwe3WylDITcC/NbD0gqWFUB4+feGwL1H7zMYnr694QQmvQ6IL29s73FN6zOYvoWduCdYrL0pUtCw0fAAUF7DC/uQ6Ifr6GdGrNRAqL7mNVbLidHvTIePDzF6ZEMxeZ/26ViEsvl1xslc7L2I6vcw/9Kn5PICHGyz3rp9umdhaI7+i6j2IyXwHo=
    
before_install:
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
    - "echo \"export MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx2g'\" > ~/.mavenrc"
install: true

script: mvn clean verify

after_success:
- . /tmp/BuildUtilities/travis-ci/deploy.sh domains releng/tools.vitruv.domains.updatesite.aggregated final vitruv-tools updatesite