name: CI

on:
  push:
    branches: [master]
  create:
    tags:
  pull_request:
  schedule:
    - cron: '15 4 * * *' # run nightly at 4:00 am

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/MANIFEST.MF') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and Verify
        run: ./mvnw -B clean verify
            -Dstyle.color=always
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.core.resolver.DefaultTychoResolver=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.tycho.osgi.configuration.MavenContextConfigurator=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.sisu.equinox.launching.internal.DefaultEquinoxLauncher=warn
            -Dorg.slf4j.simpleLogger.log.org.eclipse.xtext.maven.XtextGenerateMojo=warn
            -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.NoOpLog
        env: 
          MAVEN_OPTS: -Djansi.force=true
      - name: Publish Nightly Update Site
        if: github.ref == 'refs/heads/master' && github.repository_owner == 'vitruv-tools'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.UPDATE_SITE_DEPLOY_KEY }}
          external_repository: vitruv-tools/updatesite
          destination_dir: nightly/domains/automotive
          publish_dir: releng/tools.vitruv.domains.automotive.updatesite.aggregated/target/final
          publish_branch: master
      - name: Determine Release Version
        if: startsWith(github.ref, 'refs/tags/releases/') && github.repository_owner == 'vitruv-tools'
        id: releaseVersion
        uses: little-core-labs/get-git-tag@v3.0.2
        with:
           tagRegex: "releases/(.*)"
      - name: Publish Release Update Site
        if: startsWith(github.ref, 'refs/tags/releases/') && github.repository_owner == 'vitruv-tools'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.UPDATE_SITE_DEPLOY_KEY }}
          external_repository: vitruv-tools/updatesite
          destination_dir: release/domains/automotive/${{ steps.releaseVersion.outputs.tag }}
          publish_dir: releng/tools.vitruv.domains.automotive.updatesite.aggregated/target/final
          publish_branch: master
          
